sudo: required

language: python

services:
  - docker

before_install:
  - docker build --tag simple_python_rest_api .
  - docker run -p 127.0.0.1:5002:5002 -d simple_python_rest_api
  
python:
    - "2.7"

install:
  - pip install pytest
  
script:
  - py.test -v -l
  